import type { Metadata } from "next";
// import { Geist, Geist_Mono, Roboto } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// const robotoFont = Roboto({
//   subsets: ["vietnamese"],
//   weight: ["100", "300"],
// });

const myFont = localFont({
  src: [
    {
      path: "./StoryScript-Regular.ttf",
      weight: "100",
    },
    {
      path: "./Oswald-SemiBold.ttf",
      weight: "400",
    },
  ],
  display: "swap",
  variable: "--font-oslawd",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${myFont.variable}`}>{children}</body>
    </html>
  );
}

//tham khảo local font ở đây https://nextjs.org/docs/app/getting-started/fonts
